### ISSUE TITLE
xi:include doesn't seem to use the same loader as render_response

### ISSUE THREAD

**Issue by elistevens** [dag/flask-genshi#14]
I have a directory structure set up like this:

```
webapp/templates/boilerplate/header.xml
webapp/
   myblueprint/
       templates/
           foo.xml
       controller.py
```

Inside of foo.xml I'm trying to:

```
   <xi:include href="boilerplate/header.xml"></xi:include>
```

But I keep getting this error, no matter how I spell it:

```
 File "build/bdist.macosx-10.6-intel/egg/genshi/template/loader.py",
line 246, in load
   raise TemplateNotFound(filename, search_path)
TemplateNotFound: Template "/boilerplate/header.xml" not found
```

At the top of the controller in question, I have the following code:

```
   for x in app.genshi_instance.template_loader.search_path:
       try:
           print x
           print x('boilerplate/header.xml')
       except Exception, e:
           print e
           pass
```

Which produces:

```
<function _load_from_directory at 0x104b492a8>
('/.../webapp/templates/boilerplate/header.xml',
'boilerplate/header.xml', <open file
'/.../webapp/templates/boilerplate/header.xml', mode 'U' at
0x104b27a50>, <function _uptodate at 0x104b49488>)
<function _dispatch_by_prefix at 0x104b49410>
Template "boilerplate/header.xml" not found
```

Similarly, if I try to access 'otherblueprint/something.xml' from the controller, the _dispatch_by_prefix finds it, but generates a TemplateNotFound error inside of the template.

Any idea why?

**Comment by dag** [comment]
XIncludes in Genshi are relative to the including template _file_. I agree this is counterintuitive but it's upstream behavior and not even something Flask-Genshi could easily work around I think. Blueprint templates are not supported in master; there's support in the rewrite branch yet to be released.

**Comment by elistevens** [comment]
When I'd skimmed the docs for xi:include at:

http://genshi.edgewall.org/wiki/Documentation/xml-templates.html#id10

I took "So if the example above was in the file "myapp/index.html" (relative to the template search path)" to mean that the template search path was in use, but obviously when I read it again now, I see that you're correct.

Sorry for the noise, and thanks for the nice plugin - aside from my inability to read the docs, it's working well.  ;)
